blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://muhammad-fiaz.github.io/argparse-c/
    about: Check the documentation
  - name: Discussions
    url: https://github.com/muhammad-fiaz/argparse-c/discussions
    about: Ask questions and discuss
