#include "argparse_internal.h"
#include "argparse-c/argparse_manpage.h"

#include <stdio.h>
#include <string.h>

static void manpage_escape(FILE *fp, const char *str)
{
    if (!str) return;
    for (const char *p = str; *p; p++) {
        switch (*p) {
        case '\\': fputs("\\\\", fp); break;
        case '-':  fputs("\\-", fp); break;
        case '.':  fputs("\\&.", fp); break;
        case '\'': fputs("\\(aq", fp); break;
        default:   fputc(*p, fp); break;
        }
    }
}

static const char *type_name(argparse_type type)
{
    switch (type) {
    case ARGPARSE_TYPE_STRING:  return "string";
    case ARGPARSE_TYPE_INT:     return "integer";
    case ARGPARSE_TYPE_UINT:    return "unsigned integer";
    case ARGPARSE_TYPE_FLOAT:   return "float";
    case ARGPARSE_TYPE_DOUBLE:  return "double";
    case ARGPARSE_TYPE_BOOL:    return "boolean";
    case ARGPARSE_TYPE_ENUM:    return "choice";
    case ARGPARSE_TYPE_NONE:    return "none";
    default:                    return "string";
    }
}

static void manpage_write_header(FILE *fp, const struct argparse *parser)
{
    const char *prog = parser->prog ? parser->prog : "program";

    fprintf(fp, ".\\\" Man page for %s\n", prog);
    fprintf(fp, ".\\\" Generated by argparse-c\n");
    fprintf(fp, ".TH %s 1\n", prog);
    fprintf(fp, ".SH NAME\n");
    fprintf(fp, "%s", prog);
    if (parser->description) {
        fprintf(fp, " \\- ");
        manpage_escape(fp, parser->description);
    }
    fprintf(fp, "\n");
}

static void manpage_write_synopsis(FILE *fp, const struct argparse *parser)
{
    const char *prog = parser->prog ? parser->prog : "program";

    fprintf(fp, ".SH SYNOPSIS\n");
    fprintf(fp, ".B %s", prog);

    for (size_t i = 0; i < parser->option_count; i++) {
        const struct argparse_option *opt = &parser->options[i];
        if (opt->short_name && opt->long_name) {
            fputs(" [\\fB\\-", fp);
            fputc(opt->short_name, fp);
            fputs("\\fP | \\fB\\-\\-", fp);
            fputs(opt->long_name, fp);
            fputs("\\fP]", fp);
        } else if (opt->short_name) {
            fputs(" [\\fB\\-", fp);
            fputc(opt->short_name, fp);
            fputs("\\fP]", fp);
        } else if (opt->long_name) {
            fputs(" [\\fB\\-\\-", fp);
            fputs(opt->long_name, fp);
            fputs("\\fP]", fp);
        }
        if (opt->nargs == ARGPARSE_NARGS_1 || opt->nargs == ARGPARSE_NARGS_2 ||
            opt->nargs == ARGPARSE_NARGS_3) {
            const char *mv = opt->metavar ? opt->metavar : type_name(opt->type);
            fprintf(fp, " \\fI%s\\fP", mv);
        }
    }

    for (size_t i = 0; i < parser->positional_count; i++) {
        const struct argparse_option *pos = &parser->positionals[i];
        const char *mv = pos->metavar ? pos->metavar : type_name(pos->type);
        if (pos->nargs == ARGPARSE_NARGS_STAR || pos->nargs == ARGPARSE_NARGS_PLUS) {
            fprintf(fp, " \\fI%s\\fP...", mv);
        } else if (pos->nargs == ARGPARSE_NARGS_QUESTION) {
            fprintf(fp, " [\\fI%s\\fP]", mv);
        } else {
            fprintf(fp, " \\fI%s\\fP", mv);
        }
    }

    fprintf(fp, "\n");
}

static void manpage_write_description(FILE *fp, const struct argparse *parser)
{
    fprintf(fp, ".SH DESCRIPTION\n");
    if (parser->description) {
        manpage_escape(fp, parser->description);
        fprintf(fp, "\n");
    } else {
        fprintf(fp, "No description available.\n");
    }
    if (parser->epilog) {
        fprintf(fp, "\n");
        manpage_escape(fp, parser->epilog);
        fprintf(fp, "\n");
    }
}

static void manpage_write_options(FILE *fp, const struct argparse *parser)
{
    if (parser->option_count == 0 && parser->positional_count == 0)
        return;

    fprintf(fp, ".SH OPTIONS\n");

    for (size_t i = 0; i < parser->option_count; i++) {
        const struct argparse_option *opt = &parser->options[i];

        fprintf(fp, ".TP\n");

        if (opt->short_name && opt->long_name) {
            fputs("\\fB\\-", fp);
            fputc(opt->short_name, fp);
            fputs("\\fP, \\fB\\-\\-", fp);
            fputs(opt->long_name, fp);
            fputs("\\fP", fp);
        } else if (opt->short_name) {
            fputs("\\fB\\-", fp);
            fputc(opt->short_name, fp);
            fputs("\\fP", fp);
        } else if (opt->long_name) {
            fputs("\\fB\\-\\-", fp);
            fputs(opt->long_name, fp);
            fputs("\\fP", fp);
        }

        if (opt->nargs == ARGPARSE_NARGS_1 || opt->nargs == ARGPARSE_NARGS_2 ||
            opt->nargs == ARGPARSE_NARGS_3) {
            const char *mv = opt->metavar ? opt->metavar : type_name(opt->type);
            fprintf(fp, " \\fI%s\\fP", mv);
        }

        fprintf(fp, "\n");

        if (opt->help) {
            fprintf(fp, "    ");
            manpage_escape(fp, opt->help);
            fprintf(fp, "\n");
        }

        if (opt->choices.count > 0) {
            fprintf(fp, "    Allowed values: ");
            for (size_t c = 0; c < opt->choices.count; c++) {
                if (c > 0) fprintf(fp, ", ");
                fprintf(fp, "\\fI%s\\fP", opt->choices.items[c]);
            }
            fprintf(fp, ".\n");
        }

        if (opt->default_value) {
            fprintf(fp, "    Default: \\fI%s\\fP.\n", opt->default_value);
        }

        if (opt->required) {
            fprintf(fp, "    \\fBRequired.\\fP\n");
        }
    }

    for (size_t i = 0; i < parser->positional_count; i++) {
        const struct argparse_option *pos = &parser->positionals[i];

        fprintf(fp, ".TP\n");
        const char *mv = pos->metavar ? pos->metavar : type_name(pos->type);
        if (pos->nargs == ARGPARSE_NARGS_STAR || pos->nargs == ARGPARSE_NARGS_PLUS) {
            fprintf(fp, "\\fI%s\\fP ...", mv);
        } else if (pos->nargs == ARGPARSE_NARGS_QUESTION) {
            fprintf(fp, "[\\fI%s\\fP]", mv);
        } else {
            fprintf(fp, "\\fI%s\\fP", mv);
        }
        fprintf(fp, "\n");

        if (pos->help) {
            fprintf(fp, "    ");
            manpage_escape(fp, pos->help);
            fprintf(fp, "\n");
        }

        if (pos->required) {
            fprintf(fp, "    \\fBRequired.\\fP\n");
        }
    }
}

static void manpage_write_examples(FILE *fp, const struct argparse *parser)
{
    const char *prog = parser->prog ? parser->prog : "program";

    fprintf(fp, ".SH EXAMPLES\n");
    fprintf(fp, ".TP\n");
    fprintf(fp, "Show help:\n");
    fprintf(fp, ".B %s --help\n", prog);
    fprintf(fp, ".TP\n");
    fprintf(fp, "Show version:\n");
    fprintf(fp, ".B %s --version\n", prog);
}

static void manpage_write_footer(FILE *fp)
{
    fprintf(fp, ".SH SEE ALSO\n");
    fprintf(fp, "Full documentation at: https://github.com/argparse-c/argparse-c\n");
    fprintf(fp, ".SH AUTHORS\n");
    fprintf(fp, "argparse-c contributors.\n");
}

int argparse_generate_manpage(const struct argparse *parser, FILE *fp)
{
    if (!parser || !fp)
        return -1;

    manpage_write_header(fp, parser);
    manpage_write_synopsis(fp, parser);
    manpage_write_description(fp, parser);
    manpage_write_options(fp, parser);
    manpage_write_examples(fp, parser);
    manpage_write_footer(fp);

    return 0;
}

int argparse_generate_manpage_file(const struct argparse *parser,
                                   const char *filename)
{
    if (!parser || !filename)
        return -1;

    FILE *fp = fopen(filename, "w");
    if (!fp)
        return -1;

    int result = argparse_generate_manpage(parser, fp);
    fclose(fp);
    return result;
}
